name: Deploy to AWS Lambda via ECR

on:
  push:
    branches: [main]  
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to ECR
      env:
        ECR_REPO: ${{ secrets.ECR_REPO }}
      run: |
        IMAGE_TAG=latest
        docker build -t $ECR_REPO:$IMAGE_TAG .
        docker push $ECR_REPO:$IMAGE_TAG

    - name: Update Lambda function with new image
      env:
        FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        ECR_REPO: ${{ secrets.ECR_REPO }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws lambda update-function-code \
          --function-name $FUNCTION_NAME \
          --image-uri $ECR_REPO:latest \
          --region $AWS_REGION
